### ISSUE TITLE
Icon issue

### ISSUE THREAD

**Issue by hungkail** [YuhanLin1105/pat-ui#11]
App crash while using
```
<Icon/> | <Icon name="" /> | <Icon name="not_exist"/>
```
![image](https://user-images.githubusercontent.com/25168011/89738196-ada5e200-da2b-11ea-9927-8f3d004f9ad3.png)

**Comment by AdamYoung1234** [comment]
The problem is related to [line 133](https://github.com/YuhanLin1105/pat-ui/blob/bf5ab4c4ff1e33c7a406de57e4eccb1748ba214c/src/components/Icon/Icon.tsx#L133) in `Icon.tsx` which does not check for undefined `IconPath[name]`. You can work around with it by adding check after line 100 and return <></> if `IconPath[name]` is undefined.
